name: 'Dependency Check'
description: 'Github action to execute dependency check as part of a github workflow'
Author: 'javixeneize'
branding:
  icon: 'shield'  
  color: 'red'
inputs:
    project:
        required: true
    path:
        required: true  
    format:
        required: true
    out:
        required: true
        default: 'reports'
    oss-index-username:
        required: false
    oss-index-password:
        required: false

    args:
        required: false
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:

        - '--project'
        - '${{ inputs.project }}'
        - '--scan'
        - '/workspace/${{ inputs.path }}'
        - '--format' 
        - '${{ inputs.format }}'
        - '--out'
        - '/workspace/${{ inputs.out }}'
        - '--noupdate'
        - '--ossIndexUsername'
        - '${{ inputs.oss-index-username }}'
        - '--ossIndexPassword'
        - '${{ inputs.oss-index-password }}'
        - ${{ inputs.args }}
